In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:/files/archive_dataset/Students Social Media Addiction.csv")

In [3]:
df.head(5)

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

In [4]:
print(f"the number of duplicates is {df.duplicated().sum()}")

the number of duplicates is 0

In [5]:
df.shape

(705, 13)

In [6]:
avg_age=df['Age'].mean()
avg_age

np.float64(20.659574468085108)

In [14]:
filt=(df['Age']<avg_age) & (df['Mental_Health_Score']<=5) 
print("people with low mental health under the age 20")
df[filt]['Gender'].value_counts()

people with low mental health under the age 20

Gender
Female    94
Male      23
Name: count, dtype: int64

In [8]:
df['Relationship_Status'].unique()

array(['In Relationship', 'Single', 'Complicated'], dtype=object)

In [9]:
print(f"the least addicted score: {df['Addicted_Score'].min()}")
print(f"the most addicted score: {df['Addicted_Score'].max()}")

the least addicted score: 2
the most addicted score: 9

In [10]:
filt=df['Addicted_Score']>5
print("Relationship status distribution for people with high addiction score:")
df[filt]['Relationship_Status'].value_counts()

Relationship status distribution for people with high addiction score:

Relationship_Status
Single             276
In Relationship    166
Complicated         27
Name: count, dtype: int64

In [33]:
print("average nightly sleep hours across different relationship categories")
df.groupby('Relationship_Status')['Sleep_Hours_Per_Night'].mean()

average nightly sleep hours across different relationship categories

Relationship_Status
Complicated        5.900000
In Relationship    6.830104
Single             6.978906
Name: Sleep_Hours_Per_Night, dtype: float64

In [4]:
df['Most_Used_Platform'].unique()

array(['Instagram', 'Twitter', 'TikTok', 'YouTube', 'Facebook',
       'LinkedIn', 'Snapchat', 'LINE', 'KakaoTalk', 'VKontakte',
       'WhatsApp', 'WeChat'], dtype=object)

In [12]:
print("the most used apps by avg daily use:")
df.groupby("Most_Used_Platform")["Avg_Daily_Usage_Hours"].agg(['count','mean'])\
.sort_values(by="count",ascending=False)

the most used apps by avg daily use:

                    count      mean
Most_Used_Platform
Instagram             249  4.872289
TikTok                154  5.346104
Facebook              123  4.507317
WhatsApp               54  6.475926
Twitter                30  4.870000
LinkedIn               21  2.519048
WeChat                 15  4.960000
Snapchat               13  5.092308
LINE                   12  3.250000
KakaoTalk              12  4.725000
VKontakte              12  4.250000
YouTube                10  4.080000

In [26]:
print("the most academic level addicted to social media by avg daily use and mental health:")
df.groupby(["Academic_Level"])[["Avg_Daily_Usage_Hours",'Mental_Health_Score']]\
    .mean().sort_values(by="Avg_Daily_Usage_Hours",ascending=False)

the most academic level addicted to social media by avg daily use and mental health:

                Avg_Daily_Usage_Hours  Mental_Health_Score
Academic_Level
High School                  5.544444             5.111111
Undergraduate                5.001416             6.178470
Graduate                     4.776923             6.372308

In [27]:
df['Conflicts_Over_Social_Media'].unique()

array([3, 0, 4, 1, 2, 5])

In [30]:
print("the corelation between Daily_Usage_Hours and Conflicts_Over_Social_Media: ")
print(df['Avg_Daily_Usage_Hours'].corr(df['Conflicts_Over_Social_Media']))

the corelation between Daily_Usage_Hours and Conflicts_Over_Social_Media:
0.8045823292245056

In [39]:
print("the corelation between Daily_Usage_Hours and mental health: ")
print(df['Avg_Daily_Usage_Hours'].corr(df['Mental_Health_Score']))

the corelation between Daily_Usage_Hours and mental health:
-0.8010576231623433

In [41]:
print('Relationship Between Daily Usage Hours and Academic Performance:')
df.groupby('Affects_Academic_Performance')['Avg_Daily_Usage_Hours'].mean()

Relationship Between Daily Usage Hours and Academic Performance:

Affects_Academic_Performance
No     3.804365
Yes    5.538631
Name: Avg_Daily_Usage_Hours, dtype: float64

In [43]:
print('the corelation between Sleep_Hours_Per_Night and mental health:')
print(df['Sleep_Hours_Per_Night'].corr(df['Mental_Health_Score']))

the corelation between Sleep_Hours_Per_Night and mental health:
0.707438679121283

In [52]:
print("the top 5 platforms with the lower mental health users:")
df.groupby('Most_Used_Platform')['Mental_Health_Score'].mean()\
    .sort_values(ascending=True).head(5)

the top 5 platforms with the lower mental health users:

Most_Used_Platform
WhatsApp     5.537037
Snapchat     5.538462
TikTok       5.714286
KakaoTalk    6.000000
Instagram    6.124498
Name: Mental_Health_Score, dtype: float64